name: CI

on:
  push:
    branches:
      - main
      - ci-build-to-pages

jobs:
  Render-and-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render all slide decks
        run: |
          mkdir -p slides/output
          cd slides
          for f in *.qmd; do
            quarto render $f
            cp ${f%.qmd}.html output/${f%.qmd}.html
          done
          ls -lh output
        shell: bash -x -euo pipefail {0}

      - name: Generate Directory Listings
        uses: jayanta525/github-pages-directory-listing@v3.0.0
        with:
          FOLDER: ./slides/output

      - run: ls -lh slides/output

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./slides/output
