name: CI

on:
  - push
  - pull_request

jobs:
  Quarto-Render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render all slide decks
        run: |
          cd slides
          for f in *.qmd; do
            quarto render $f
          done
        shell: bash -x -euo pipefail {0}
